project_name: content-plus-totp
before:
  hooks:
    - go mod tidy

builds:
  - main: main.go 
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w -X github.com/iomarmochtar/content-plus-totp/app.Version={{.Version}}

checksum:
  name_template: 'checksums.txt'

archives:
  - files:
      # Only include built binary in archive
      - 'none*'
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'