name: tests
on: [pull_request, workflow_dispatch]

env:
  GO_VERSION: 1.17
  CGO_ENABLED: 0

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  
  unit-test:
    name: unit-test 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install required packages
        run: sudo apt install -y make
      - run: make test 
      - name: Upload Codecov report
        uses: codecov/codecov-action@v2.1.0
        with:
          files: coverage.txt
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}